name: AllocationClearance
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.10.6
  - conda-forge::pip=22.2
  - conda-forge::sqlalchemy=1.4.40
  - conda-forge::pyodbc=4.0
  - conda-forge::pandas=1.4.3
  - conda-forge::numpy=1.23.2
  - conda-forge::pytest=7.1.3
  - conda-forge::black=22.6.0
  - conda-forge::pyyaml=6.0
  - conda-forge::scikit-learn=1.1.2
  - conda-forge::scipy=1.9.1
  - conda-forge::lightgbm=3.3.2
  - conda-forge::ipython=8.4
  - conda-forge::ipykernel=6.15.2
  - conda-forge::pylint=2.15.2
  - conda-forge::click=8.1.3
